---
- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __vault_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars
  tags: always

- name: Execute os-specific tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __vault_tasks_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: Start master vault services
  systemd:
    state: started
    name: vault
    daemon_reload: true
    enabled: true
  when: __vault_is_master

- name: In-place init-unseal
  include_tasks: _inplace_init_unseal.yml
  when:
    - vault_unseal_method == 'in-place'
    - __vault_is_master

- name: Flush before leaving
  meta: flush_handlers
  tags: always
