---

- name: Restart vault
  service:
    name: vault
    state: restarted
    enabled: true

- name: Update ca trust
  command: >-
    /usr/sbin/update-ca-certificates

- name: Parse unseal status
  when: vault_init_results is defined
  set_fact:
    vault_init_parsed: "{{ vault_init_results.stdout | from_json }}"
